server:
  port: 9082
feign:
  hystrix:
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false
    username: developer
    password: password
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: messages_jp
    cache-duration: -1
